version: 2

python:
  install:
    - requirements: doc/requirements-rtfd.txt
    - requirements: requirements-dev.txt
    - method: setuptools
      path: .
      extra_requirements:
        - midi
        - ui
