version: 2

build:
  os: 'ubuntu-20.04'
  tools:
    python: '3.8'
python:
  install:
    - requirements: doc/requirements-rtfd.txt
    - requirements: requirements-dev.txt
    - method: pip
      path: .
      extra_requirements:
        - midi
        - ui
